version: '3'

services: 
  db:
    image: mongo:5
    ports: 
      - 27019:27017
    environment:
      MONGODB_DATABASE: tattoo-manager
      MONGODB_USERNAME: ${MONGO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db       
volumes:
  mongodata:      